# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PERL=5.20.3.1  CONDA_PY=27
    - CONDA_PERL=5.22.0.1  CONDA_PY=27
    - CONDA_PERL=5.22.2.1  CONDA_PY=27
    - CONDA_PERL=5.20.3.1  CONDA_PY=35
    - CONDA_PERL=5.22.0.1  CONDA_PY=35
    - CONDA_PERL=5.22.2.1  CONDA_PY=35
    - CONDA_PERL=5.20.3.1  CONDA_PY=36
    - CONDA_PERL=5.22.0.1  CONDA_PY=36
    - CONDA_PERL=5.22.2.1  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "k8byTIDXJFN7SDp+fErKjSPckF9xjvGM5JQpKTLWFpy/uEp2lNSuJR2M+8Qb/TbmoOi6fBLWm/fVBu/Up/8PCIt+cy7u3w3h0UA2dVEICaPKsAGASW5Hy8D/qaIBI0vrAPU4xy8jqKgpJ6x1kkG08O+5/g1R7qytwJ+m0K32Lf47qsMl6cJwaH58aBfgfFNZQwGfFppl/Ob3t4QW2HPUW8k0dL0dmrsnThIOLSq9ZhBniPquDhyVYIiCGsucXNOqffCd7w0gWKv/bJWWG/lzAVb3sXmBtzoXNMA0q1LuvNJXBv57Q32A+jCybbMaZQTq2zKHXVJOIYL9gDWN8lT7d+HFwSHC/B8HK2icrBC+6Upmib6Aebw+UhwrXXev0mK0s40CRB4fSYuP2w46yuNK6xuiWXR04mHugd5eqF4ie5tzDQkrO8Nd/o0FeKNJKeH66xD7LyxxIiv5wFIMSiMs8g8FOzzvr/ldq90HHLFC/PVvnBLiSMiIKK71xfr7VchBRNM7BeU00+th4RWDCSLMQdj8xV1NdgjSuVfsMuYAAZtHbUe8WA3QcdauR3xPRTB9RV3gWw+s1x8q2jeMUKhbsy9o/QA1pOhDRqf7j76iQ2B/2xbCF9n+QtzaB5BpMkvzN5S5nm0/M7P+4ammgseUHvMHyUZX6g0D+RA/PaUkGmo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
