travis:
  secure:
    BINSTAR_TOKEN: uTVSnmYDypkPKW/RAEcV1zpikaHnOo3Cg2fcLOKSQNrIEx2dj7zOyE5lFraeSauRLqXCpKp+qMXmr7PEEiEreeME5wqwYXjxvqGXtfgkxcwPzQaDQO77iSPH4Dw5SaS37n2Bzhgko1agAPB8ERmgu0N5AAoYufWbznIaNbwuAMzYNr4iJtKDbVVrLx9WLCB7Lm8kpZ5uwFJ3n3mYZO8d5qpeHhKxdQR/C8d+R3dsuch5d6iuXJjbBj/n9CoKfMjQhBI8nQmiWlAVyO5pKh/MhQnCluTYG8bKWxNmKLw3DsFxlmVryyeNZxLd2Z3YTBgpZ9aZAqX15EQ98J47e6K6Xu5fmOqJAwfzflo75a8DUlqJoN5Qe94lJyMEc1gBBwJ/ZIprUmYOy5GKmYKTPe30NlNb8Jm8x12VQEjnM2z1AQsdiRKFdyly4wDEKICbksNjTj65221UHb2RiRsFbAzR48aby0MkmvGcXNhCtC65YVxuHjRp615yMYI2Pd0ITQDR0sp9N4X+dS4KpTF7TSl2v3pnBZ3Magn2y15A6Dq06JEexjwJGup8z2mh9oq3l2I3zOqTOaG7PX2mq4qGfAlqv1Zft+6hWfWBx9q08xa+RxcJFYrJMZYywZ9kWmmO9oOg6U63ZawdZTWif/PIhU/u9y34r8iHcHQTC3wAd9ttJKw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
