travis:
  secure:
    BINSTAR_TOKEN: k8byTIDXJFN7SDp+fErKjSPckF9xjvGM5JQpKTLWFpy/uEp2lNSuJR2M+8Qb/TbmoOi6fBLWm/fVBu/Up/8PCIt+cy7u3w3h0UA2dVEICaPKsAGASW5Hy8D/qaIBI0vrAPU4xy8jqKgpJ6x1kkG08O+5/g1R7qytwJ+m0K32Lf47qsMl6cJwaH58aBfgfFNZQwGfFppl/Ob3t4QW2HPUW8k0dL0dmrsnThIOLSq9ZhBniPquDhyVYIiCGsucXNOqffCd7w0gWKv/bJWWG/lzAVb3sXmBtzoXNMA0q1LuvNJXBv57Q32A+jCybbMaZQTq2zKHXVJOIYL9gDWN8lT7d+HFwSHC/B8HK2icrBC+6Upmib6Aebw+UhwrXXev0mK0s40CRB4fSYuP2w46yuNK6xuiWXR04mHugd5eqF4ie5tzDQkrO8Nd/o0FeKNJKeH66xD7LyxxIiv5wFIMSiMs8g8FOzzvr/ldq90HHLFC/PVvnBLiSMiIKK71xfr7VchBRNM7BeU00+th4RWDCSLMQdj8xV1NdgjSuVfsMuYAAZtHbUe8WA3QcdauR3xPRTB9RV3gWw+s1x8q2jeMUKhbsy9o/QA1pOhDRqf7j76iQ2B/2xbCF9n+QtzaB5BpMkvzN5S5nm0/M7P+4ammgseUHvMHyUZX6g0D+RA/PaUkGmo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
